import { Language } from './i18n/translations';

// 人生事件卡数据库
// 每个事件影响 4 个属性：money（资产）, hair（发量）, iq（智力）, happiness（快乐）

export interface LifeEvent {
       id: string;
       title: string;
       description: string;
       emoji: string;
       image?: string;
       category: 'work' | 'social' | 'life' | 'random';
       isKey?: boolean; // 关键事件，权重翻倍
       optionA: {
              text: string;
              effects: { money?: number; hair?: number; iq?: number; happiness?: number; social?: number; health?: number };
       };
       optionB: {
              text: string;
              effects: { money?: number; hair?: number; iq?: number; happiness?: number; social?: number; health?: number };
       };
}

export const lifeEventsZh: LifeEvent[] = [
       // ===== 职场类 =====
       {
              id: 'work_996',
              title: '996 邀请函',
              description: '老板邀请你加入核心项目，需要996但承诺年终奖翻倍',
              emoji: '💼',
              image: '/images/events/work_996.png',
              category: 'work',
              isKey: true,
              optionA: { text: '接受挑战', effects: { money: 30, hair: -25, happiness: -15 } },
              optionB: { text: '婉拒保命', effects: { happiness: 15, money: -5 } },
       },
       {
              id: 'work_promotion',
              title: '晋升机会',
              description: '有个管理岗位空缺，但需要你负责更多事务',
              emoji: '📈',
              image: '/images/events/work_promotion.webp',
              category: 'work',
              optionA: { text: '冲！', effects: { money: 20, iq: 10, hair: -15, happiness: -5 } },
              optionB: { text: '躺平挺好', effects: { happiness: 15, hair: 5 } },
       },
       {
              id: 'work_deadline',
              title: '紧急 Deadline',
              description: '项目要提前交付，需要连续加班三天',
              emoji: '⏰',
              image: '/images/events/work_deadline.png',
              category: 'work',
              optionA: { text: '熬夜赶工', effects: { money: 15, hair: -25, happiness: -15 } },
              optionB: { text: '申请延期', effects: { iq: 10, money: -10 } },
       },
       {
              id: 'work_side',
              title: '副业机会',
              description: '朋友邀请你一起做个小项目，可能赚钱也可能白忙',
              emoji: '🚀',
              image: '/images/events/work_side.webp',
              category: 'work',
              optionA: { text: '搞起来', effects: { money: 25, hair: -10, iq: 5 } },
              optionB: { text: '专注主业', effects: { happiness: 10, hair: 5 } },
       },

       // ===== 社交类 =====
       {
              id: 'social_party',
              title: '周末聚会',
              description: '朋友喊你周末去 KTV，你已经累了一周',
              emoji: '🎤',
              image: '/images/events/social_party.webp',
              category: 'social',
              isKey: true,
              optionA: { text: '嗨起来', effects: { happiness: 25, money: -20, hair: -5 } },
              optionB: { text: '在家躺着', effects: { hair: 10, happiness: -5 } },
       },
       {
              id: 'social_date',
              title: '心动约会',
              description: '有个心仪的人约你吃饭，但今晚你有个重要会议',
              emoji: '💕',
              image: '/images/events/social_date.webp',
              category: 'social',
              optionA: { text: '赴约！', effects: { happiness: 25, money: -10, iq: -5 } },
              optionB: { text: '工作优先', effects: { money: 15, happiness: -20 } },
       },
       {
              id: 'social_help',
              title: '朋友求助',
              description: '好友搬家需要帮忙，但你周末本来想休息',
              emoji: '📦',
              image: '/images/events/social_help.webp',
              category: 'social',
              optionA: { text: '义气相挺', effects: { happiness: 15, hair: -10 } },
              optionB: { text: '找借口推掉', effects: { hair: 10, happiness: -10, iq: -5 } },
       },
       {
              id: 'social_wedding',
              title: '红色炸弹',
              description: '收到婚礼请柬，份子钱不便宜',
              emoji: '💒',
              image: '/images/events/social_wedding.webp',
              category: 'social',
              optionA: { text: '出席送祝福', effects: { happiness: 10, money: -25 } },
              optionB: { text: '随个红包算了', effects: { money: -10, happiness: -5 } },
       },

       // ===== 生活类 =====
       {
              id: 'life_gym',
              title: '健身计划',
              description: '办了健身卡，今天要不要去练一下？',
              emoji: '🏋️',
              image: '/images/events/life_gym.webp',
              category: 'life',
              optionA: { text: '撸铁！', effects: { hair: 15, happiness: 10, iq: 5 } },
              optionB: { text: '明天再说', effects: { happiness: 5, hair: -5 } },
       },
       {
              id: 'life_takeout',
              title: '外卖诱惑',
              description: '深夜饿了，是吃炸鸡还是忍一忍？',
              emoji: '🍗',
              image: '/images/events/life_takeout.webp',
              category: 'life',
              optionA: { text: '吃！减什么肥', effects: { happiness: 15, hair: -5, money: -5 } },
              optionB: { text: '喝杯水睡觉', effects: { hair: 10, iq: 5 } },
       },
       {
              id: 'life_sleep',
              title: '熬夜刷剧',
              description: '追的剧更新了，但已经凌晨1点',
              emoji: '📺',
              image: '/images/events/life_sleep.webp',
              category: 'life',
              optionA: { text: '先看两集', effects: { happiness: 15, hair: -20, iq: -5 } },
              optionB: { text: '明天再看', effects: { hair: 10, iq: 5 } },
       },
       {
              id: 'life_shopping',
              title: '购物车召唤',
              description: '双十一到了，购物车里的东西在呼唤你',
              emoji: '🛒',
              image: '/images/events/life_shopping.webp',
              category: 'life',
              isKey: true,
              optionA: { text: '清空购物车', effects: { happiness: 30, money: -40 } },
              optionB: { text: '理性消费', effects: { money: 10, happiness: -5 } },
       },
       {
              id: 'life_pet',
              title: '猫咪生病',
              description: '毛孩子精神不太好，带去医院花费可能不少',
              emoji: '😿',
              image: '/images/events/life_pet.webp',
              category: 'life',
              optionA: { text: '立刻送医', effects: { money: -25, happiness: 10, iq: 5 } },
              optionB: { text: '先观察一下', effects: { happiness: -20 } },
       },

       // ===== 随机类 =====
       {
              id: 'random_lottery',
              title: '彩票站',
              description: '路过彩票站，要不要买一注？',
              emoji: '🎰',
              image: '/images/events/random_lottery.webp',
              category: 'random',
              optionA: { text: '来一注', effects: { money: -5, happiness: 10 } },
              optionB: { text: '不赌为赢', effects: { iq: 5 } },
       },
       {
              id: 'random_rain',
              title: '突然下雨',
              description: '没带伞，打车还是淋雨跑回去？',
              emoji: '🌧️',
              image: '/images/events/random_rain.webp',
              category: 'random',
              optionA: { text: '打车', effects: { money: -10, hair: 5 } },
              optionB: { text: '跑！', effects: { hair: -10, happiness: 5, iq: -5 } },
       },
       {
              id: 'random_boss',
              title: '老板请客',
              description: '老板突然请部门吃饭，但要陪酒',
              emoji: '🍺',
              image: '/images/events/random_boss.webp',
              category: 'random',
              optionA: { text: '陪喝', effects: { money: 10, hair: -15, happiness: 5 } },
              optionB: { text: '找借口溜了', effects: { happiness: 10, money: -5 } },
       },
       {
              id: 'random_invest',
              title: '理财建议',
              description: '同事推荐了一个"稳赚不赔"的投资',
              emoji: '📊',
              image: '/images/events/random_invest.webp',
              category: 'random',
              isKey: true,
              optionA: { text: '跟一把', effects: { money: 30, iq: -10, happiness: -5 } },
              optionB: { text: '谨慎拒绝', effects: { iq: 15, money: 5 } },
       },
       {
              id: 'random_coffee',
              title: '咖啡续命',
              description: '下午犯困，来杯咖啡提神？',
              emoji: '☕',
              image: '/images/events/random_coffee.webp',
              category: 'random',
              optionA: { text: '来一杯', effects: { iq: 10, money: -5, hair: -5 } },
              optionB: { text: '困了就睡', effects: { hair: 10, iq: -5 } },
       },
       {
              id: 'random_resign',
              title: '裸辞冲动',
              description: '工作太累了，想立刻辞职',
              emoji: '🚪',
              image: '/images/events/random_resign.webp',
              category: 'random',
              isKey: true,
              optionA: { text: '冲动辞职', effects: { happiness: 40, money: -40, hair: 20 } },
              optionB: { text: '忍忍再说', effects: { money: 15, happiness: -15, hair: -10 } },
       },

       // ===== 扩充事件 =====
       // Work - 职场
       {
              id: 'work_ai',
              title: 'AI 危机',
              description: '公司引进了AI，老板暗示该岗位未来可能不需要你了',
              emoji: '🤖',
              image: '/images/events/work_ai.png',
              category: 'work',
              optionA: { text: '学习AI', effects: { iq: 15, hair: -10, money: -5 } },
              optionB: { text: '拔掉AI电源', effects: { happiness: 20, money: -20, hair: 5 } },
       },
       {
              id: 'work_toilet',
              title: '带薪拉屎',
              description: '唯一的马桶被占了1小时，你快憋不住了',
              emoji: '🚽',
              image: '/images/events/work_toilet.png',
              category: 'work',
              optionA: { text: '敲门催促', effects: { social: -5, happiness: -5 } },
              optionB: { text: '去老板厕所', effects: { happiness: 10, money: -10 } }, // 扣钱因为可能被发现
       },
       {
              id: 'work_pot',
              title: '天降黑锅',
              description: '项目炸了，领导暗示是你的责任',
              emoji: '🍳',
              image: '/images/events/work_pot.png',
              category: 'work',
              isKey: true,
              optionA: { text: '忍辱负重', effects: { money: 10, happiness: -20, hair: -5 } },
              optionB: { text: '掀桌辞职', effects: { happiness: 30, money: -30 } },
       },
       {
              id: 'work_teambuilding',
              title: '强制团建',
              description: '周末去荒郊野岭搞"素质拓展"，自费',
              emoji: '🧗',
              image: '/images/events/work_teambuilding.png',
              category: 'work',
              optionA: { text: '假装积极', effects: { money: -10, happiness: -15, hair: -5 } },
              optionB: { text: '装病请假', effects: { iq: 5, happiness: 5, money: -5 } },
       },
       {
              id: 'work_ppt',
              title: 'PPT 造车',
              description: '无论做得多烂，只要PPT好看就能拿奖',
              emoji: '📽️',
              image: '/images/events/work_ppt.png',
              category: 'work',
              optionA: { text: '美化PPT', effects: { iq: -5, money: 15, hair: -10 } },
              optionB: { text: '实事求是', effects: { money: -5, happiness: 5 } },
       },
       {
              id: 'work_gossip',
              title: '茶水间八卦',
              description: '听到关于自己的离谱谣言',
              emoji: '🤫',
              image: '/images/events/work_gossip.png',
              category: 'work',
              optionA: { text: '当面硬刚', effects: { happiness: 10, social: -10 } },
              optionB: { text: '忍气吞声', effects: { happiness: -10, iq: 5 } },
       },
       {
              id: 'work_monitor',
              title: '监控系统',
              description: '公司安装了防摸鱼监控软件',
              emoji: '👁️',
              category: 'work',
              optionA: { text: '更加努力', effects: { hair: -15, happiness: -10 } },
              optionB: { text: '物理遮挡', effects: { iq: 10, happiness: 5 } },
       },
       {
              id: 'work_coffee',
              title: '咖啡涨价',
              description: '楼下咖啡涨到50一杯，喝还是不喝？',
              emoji: '☕',
              category: 'work',
              optionA: { text: '咬牙买', effects: { money: -10, iq: 5 } },
              optionB: { text: '喝白开水', effects: { money: 5, happiness: -5 } },
       },

       // Social - 社交
       {
              id: 'social_borrow',
              title: '借钱不还',
              description: '八百年不联系的同学突然找你借钱',
              emoji: '💸',
              image: '/images/events/social_borrow.png',
              category: 'social',
              optionA: { text: '借！义气', effects: { money: -20, iq: -10, happiness: 5 } },
              optionB: { text: '拉黑', effects: { iq: 5, happiness: 5 } },
       },
       {
              id: 'social_versailles',
              title: '凡尔赛聚会',
              description: '同学会上大家都在炫富，你感到...',
              emoji: '🤮',
              category: 'social',
              optionA: { text: '比他们更炫', effects: { money: -20, happiness: 10 } },
              optionB: { text: '低头干饭', effects: { happiness: 5, money: 5 } },
       },
       {
              id: 'social_blind_date',
              title: '奇葩相亲',
              description: '对方上来就问你有几套房',
              emoji: '💘',
              image: '/images/events/social_blind_date.png',
              category: 'social',
              optionA: { text: '实话实说', effects: { happiness: -10 } },
              optionB: { text: '吹牛逼', effects: { happiness: 10, iq: 5 } },
       },
       {
              id: 'social_parents',
              title: '催婚暴击',
              description: '过年回家，七大姑八大姨围攻',
              emoji: '🧨',
              image: '/images/events/social_parents.png',
              category: 'social',
              optionA: { text: '耐心解释', effects: { happiness: -15, hair: -5 } },
              optionB: { text: '戴耳机', effects: { happiness: 5, social: -5 } },
       },
       {
              id: 'social_share',
              title: '拼单名媛',
              description: '群里问要不要拼单顶级酒店下午茶拍照',
              emoji: '🍰',
              image: '/images/events/social_share.png',
              category: 'social',
              optionA: { text: '拼！出片', effects: { money: -10, happiness: 10 } },
              optionB: { text: '不去', effects: { money: 5 } },
       },
       {
              id: 'social_like',
              title: '点赞之交',
              description: '老板发了无聊朋友圈，点不点赞？',
              emoji: '👍',
              category: 'social',
              optionA: { text: '狂赞', effects: { money: 5, happiness: -5 } },
              optionB: { text: '装没看见', effects: { happiness: 5, money: -5 } },
       },

       // Life - 生活
       {
              id: 'life_rent',
              title: '房东涨租',
              description: '房东通知下个月房租涨20%',
              emoji: '🏠',
              image: '/images/events/life_rent.png',
              category: 'life',
              isKey: true,
              optionA: { text: '含泪续租', effects: { money: -25, happiness: -10 } },
              optionB: { text: '搬到郊区', effects: { money: 10, happiness: -5, hair: -5 } },
       },
       {
              id: 'life_hair',
              title: '托尼老师',
              description: '理发师听不懂"稍微修一下"',
              emoji: '💇‍♂️',
              category: 'life',
              optionA: { text: '办卡闭嘴', effects: { money: -15, hair: 5 } },
              optionB: { text: '据理力争', effects: { hair: -10, happiness: -10 } },
       },
       {
              id: 'life_insomnia',
              title: '深夜网抑云',
              description: '凌晨三点，突然开始思考人生意义',
              emoji: '🌚',
              category: 'life',
              optionA: { text: '继续想', effects: { iq: 5, hair: -10, happiness: -10 } },
              optionB: { text: '吃褪黑素', effects: { hair: 5, money: -5 } },
       },
       {
              id: 'life_scalper',
              title: '黄牛演唱会',
              description: '偶像演唱会门票被炒到天价',
              emoji: '🎫',
              category: 'life',
              optionA: { text: '割肉买', effects: { money: -30, happiness: 25 } },
              optionB: { text: '听CD', effects: { money: 10, happiness: -5 } },
       },
       {
              id: 'life_diet',
              title: '轻食主义',
              description: '这盆草只要88元，据说很健康',
              emoji: '🥗',
              category: 'life',
              optionA: { text: '吃草', effects: { money: -10, health: 5, happiness: -5 } },
              optionB: { text: '吃麻辣烫', effects: { happiness: 10, money: 5, health: -5 } },
       },
       {
              id: 'life_game',
              title: 'Steam大促',
              description: 'G胖的微笑，钱包的哀嚎',
              emoji: '🎮',
              category: 'life',
              optionA: { text: '买买买', effects: { money: -15, happiness: 15 } },
              optionB: { text: '玩库存', effects: { money: 5, happiness: -5 } },
       },

       // Random - 随机
       {
              id: 'random_scam',
              title: '诈骗电话',
              description: '对方说他是秦始皇，需要打钱解冻兵马俑',
              emoji: '📞',
              image: '/images/events/random_scam.webp',
              category: 'random',
              optionA: { text: '打钱！', effects: { money: -20, iq: -20 } },
              optionB: { text: '反诈宣传', effects: { iq: 10, happiness: 5 } },
       },
       {
              id: 'random_toilet_drop',
              title: '手机跳水',
              description: '手机掉进厕所了...',
              emoji: '📱',
              image: '/images/events/random_toilet_drop.webp',
              category: 'random',
              optionA: { text: '伸手捞', effects: { happiness: -20, money: 5 } },
              optionB: { text: '买新的', effects: { money: -30, happiness: 10 } },
       },
       {
              id: 'random_monk',
              title: '红尘看破',
              description: '突然想出家，去山里当和尚/尼姑',
              emoji: '🧘',
              image: '/images/events/random_monk.webp',
              category: 'random',
              isKey: true,
              optionA: { text: '立刻出发', effects: { money: -50, happiness: 30, hair: -30 } },
              optionB: { text: '我就想想', effects: { happiness: -5 } },
       },
       {
              id: 'random_bug',
              title: '系统Bug',
              description: '你发现了世界的Bug，看到了一串代码',
              emoji: '👾',
              image: '/images/events/random_bug.webp',
              category: 'random',
              optionA: { text: '利用Bug', effects: { money: 50, iq: 20, happiness: 20 } },
              optionB: { text: '上报管理员', effects: { happiness: 5, iq: 5 } },
       },
       {
              id: 'random_cat',
              title: '流浪猫',
              description: '路边捡到一只绝世美猫',
              emoji: '🐈',
              image: '/images/events/random_cat.webp',
              category: 'random',
              optionA: { text: '收养', effects: { money: -10, happiness: 20 } },
              optionB: { text: '喂根肠', effects: { money: -2, happiness: 5 } },
       },
       {
              id: 'random_ufo',
              title: 'UFO 目击',
              description: '你看到了UFO，但没人信',
              emoji: '🛸',
              image: '/images/events/random_ufo.webp',
              category: 'random',
              optionA: { text: '发朋友圈', effects: { social: -5, happiness: 5 } },
              optionB: { text: '保守秘密', effects: { iq: 5 } },
       },
       {
              id: 'random_stock',
              title: '股市熔断',
              description: '千股跌停，你的基金绿得发光',
              emoji: '📉',
              image: '/images/events/random_stock.png',
              category: 'random',
              optionA: { text: '抄底！', effects: { money: -20, happiness: -5 } },
              optionB: { text: '更是割肉', effects: { money: -10, happiness: -10 } },
       },
       {
              id: 'random_influencer',
              title: '网红梦',
              description: '有人说你长得像明星，建议你做直播',
              emoji: '🎥',
              image: '/images/events/random_influencer.png',
              category: 'random',
              optionA: { text: '直播带货', effects: { money: 10, hair: -10, social: -5 } },
              optionB: { text: '我社恐', effects: { happiness: 5 } },
       },
];

export const lifeEventsEn: LifeEvent[] = [
       // ===== Work =====
       {
              id: 'work_996',
              title: 'Overtime Invitation',
              description: 'Boss asks you to join a core project (996) but promises double bonus.',
              emoji: '💼',
              category: 'work',
              optionA: { text: 'Accept Challenge', effects: { money: 25, hair: -20, happiness: -10 } },
              optionB: { text: 'Decline for Health', effects: { happiness: 10, money: -5 } },
       },
       {
              id: 'work_promotion',
              title: 'Promotion Chance',
              description: 'A management position is open, but comes with more responsibility.',
              emoji: '📈',
              category: 'work',
              optionA: { text: 'Go for it!', effects: { money: 20, iq: 10, hair: -15, happiness: -5 } },
              optionB: { text: 'Stay Chill', effects: { happiness: 15, hair: 5 } },
       },
       {
              id: 'work_deadline',
              title: 'Urgent Deadline',
              description: 'Project due earlier. Need to work late for 3 days.',
              emoji: '⏰',
              category: 'work',
              optionA: { text: 'Work All Night', effects: { money: 15, hair: -25, happiness: -15 } },
              optionB: { text: 'Ask Extension', effects: { iq: 10, money: -10 } },
       },
       {
              id: 'work_side',
              title: 'Side Hustle',
              description: 'Friend invites you to a startup. High risk, high reward?',
              emoji: '🚀',
              category: 'work',
              optionA: { text: 'Do it!', effects: { money: 20, hair: -10, iq: 5 } },
              optionB: { text: 'Focus on Job', effects: { happiness: 10, hair: 5 } },
       },

       // ===== Social =====
       {
              id: 'social_party',
              title: 'Weekend Party',
              description: 'Friends invite you to KTV, but you are tired.',
              emoji: '🎤',
              category: 'social',
              optionA: { text: 'Let\'s Party!', effects: { happiness: 20, money: -15, hair: -5 } },
              optionB: { text: 'Stay Home', effects: { hair: 10, happiness: -5 } },
       },
       {
              id: 'social_date',
              title: 'Romantic Date',
              description: 'Your crush invites you to dinner, but you have a meeting.',
              emoji: '💕',
              category: 'social',
              optionA: { text: 'Go on Date!', effects: { happiness: 25, money: -10, iq: -5 } },
              optionB: { text: 'Work First', effects: { money: 10, happiness: -15 } },
       },
       {
              id: 'social_help',
              title: 'Friend Needs Help',
              description: 'Friend moving house needs help on your rest day.',
              emoji: '📦',
              category: 'social',
              optionA: { text: 'Help Friend', effects: { happiness: 15, hair: -10 } },
              optionB: { text: 'Make Excuse', effects: { hair: 10, happiness: -10, iq: -5 } },
       },
       {
              id: 'social_wedding',
              title: 'Wedding Invite',
              description: 'Received a wedding invitation. Gift money is expensive.',
              emoji: '💒',
              category: 'social',
              optionA: { text: 'Attend & Gift', effects: { happiness: 10, money: -20 } },
              optionB: { text: 'Send Red Packet', effects: { money: -10, happiness: -5 } },
       },

       // ===== Life =====
       {
              id: 'life_gym',
              title: 'Gym Time',
              description: 'Bought a gym membership. Go workout today?',
              emoji: '🏋️',
              category: 'life',
              optionA: { text: 'Workout!', effects: { hair: 15, happiness: 10, iq: 5 } },
              optionB: { text: 'Maybe Tomorrow', effects: { happiness: 5, hair: -5 } },
       },
       {
              id: 'life_takeout',
              title: 'Late Night Snack',
              description: 'Hungry at midnight. Fried chicken or water?',
              emoji: '🍗',
              category: 'life',
              optionA: { text: 'Fried Chicken!', effects: { happiness: 15, hair: -5, money: -5 } },
              optionB: { text: 'Drink Water', effects: { hair: 10, iq: 5 } },
       },
       {
              id: 'life_sleep',
              title: 'Binge Watching',
              description: 'New episode is out, but it\'s 1 AM.',
              emoji: '📺',
              category: 'life',
              optionA: { text: 'Watch 2 eps', effects: { happiness: 15, hair: -15, iq: -5 } },
              optionB: { text: 'Sleep', effects: { hair: 10, iq: 5 } },
       },
       {
              id: 'life_shopping',
              title: 'Shopping Spree',
              description: 'Double 11 Sale! Your cart is calling you.',
              emoji: '🛒',
              category: 'life',
              optionA: { text: 'Buy All', effects: { happiness: 20, money: -25 } },
              optionB: { text: 'Be Rational', effects: { money: 10, happiness: -5 } },
       },
       {
              id: 'life_pet',
              title: 'Sick Pet',
              description: 'Your cat looks sick. Vet bill might be high.',
              emoji: '😿',
              category: 'life',
              optionA: { text: 'Go to Vet', effects: { money: -20, happiness: 10, iq: 5 } },
              optionB: { text: 'Wait & See', effects: { happiness: -15 } },
       },

       // ===== Random =====
       {
              id: 'random_lottery',
              title: 'Lottery',
              description: 'Passing a lottery shop. Buy a ticket?',
              emoji: '🎰',
              category: 'random',
              optionA: { text: 'Buy One', effects: { money: -5, happiness: 10 } },
              optionB: { text: 'No Gambling', effects: { iq: 5 } },
       },
       {
              id: 'random_rain',
              title: 'Sudden Rain',
              description: 'No umbrella. Taxi or run in rain?',
              emoji: '🌧️',
              category: 'random',
              optionA: { text: 'Taxi', effects: { money: -10, hair: 5 } },
              optionB: { text: 'Run!', effects: { hair: -10, happiness: 5, iq: -5 } },
       },
       {
              id: 'random_boss',
              title: 'Boss Treat',
              description: 'Boss invites team for dinner, but must drink alcohol.',
              emoji: '🍺',
              category: 'random',
              optionA: { text: 'Drink', effects: { money: 10, hair: -15, happiness: 5 } },
              optionB: { text: 'Escape', effects: { happiness: 10, money: -5 } },
       },
       {
              id: 'random_invest',
              title: 'Investment Tip',
              description: 'Colleague suggests a "sure win" investment.',
              emoji: '📊',
              category: 'random',
              optionA: { text: 'Invest', effects: { money: 30, iq: -10, happiness: -5 } },
              optionB: { text: 'Decline', effects: { iq: 10, money: 5 } },
       },
       {
              id: 'random_coffee',
              title: 'Coffee Break',
              description: 'Sleepy afternoon. Coffee?',
              emoji: '☕',
              category: 'random',
              optionA: { text: 'Drink Coffee', effects: { iq: 10, money: -5, hair: -5 } },
              optionB: { text: 'Take Nap', effects: { hair: 10, iq: -5 } },
       },
       {
              id: 'random_resign',
              title: 'Quit Job',
              description: 'Too tired. Want to quit job now.',
              emoji: '🚪',
              category: 'random',
              optionA: { text: 'Quit Now', effects: { happiness: 30, money: -30, hair: 20 } },
              optionB: { text: 'Endure', effects: { money: 10, happiness: -10, hair: -10 } },
       },
];

// 获取随机事件（根据语言）
export function getRandomEvents(count: number, lang: Language = 'zh'): LifeEvent[] {
       const source = lang === 'en' ? lifeEventsEn : lifeEventsZh;
       const shuffled = [...source].sort(() => Math.random() - 0.5);
       return shuffled.slice(0, count);
}

// 1分钟游戏，约 12-15 张卡
export const EVENTS_PER_GAME = 12;
export const DECISION_TIME_MS = 4000; // 每张卡 4 秒决策时间
